config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :galleries
  resources :attachments
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  has_one_attached :photo
  belongs_to :gallery, optional: true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :attachments
  belongs_to :user
  has_rich_text :description
  # accepts_nested_attributes_for :attachments

  def first_photo
    attachments.each do |attachment|
      if attachment.photo.attached?
        return attachment.photo
      end
    end
    return false
  end

  def has_photos?
    result = attachments.select do |att|
      if att.photo.attached?
        true
      end
    end
    return true if result.length > 0
    return false
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :galleries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if:  :devise_controller?

protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:display_name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:display_name, :email, :password, :current_password) }

  end  
end

app/controllers/attachments_controller.rb
class AttachmentsController < InheritedResources::Base

  before_action :authenticate_user!

  def destroy
    @attachment = Attachment.find(params[:id])
    gallery = @attachment.gallery

    if gallery.user == current_user
      @image = ActiveStorage::Attachment.find(params[:id])
      @image.purge
      @attachment.delete
    end

    redirect_to edit_gallery_path(gallery)
  end

  private

    def attachment_params
      params.require(:attachment).permit(:caption, :photo)
    end

end

app/controllers/galleries_controller.rb
class GalleriesController < InheritedResources::Base

  before_action :authenticate_user!, :except => [:index, :show]

  def new
    @attachment = Attachment.new
    @gallery = Gallery.new
  end

  def edit
    @attachment = Attachment.new
    @gallery = Gallery.find(params[:id])
    if !user_owns_gallery?(@gallery)
      redirect_to gallery_path, notice: "You cannot edit this gallery. Sign in and try again!" and return
    end
  end

  def update
    gallery = Gallery.find(params[:id])
    if !user_owns_gallery?(gallery)
      redirect_to gallery_path, notice: "You cannot update this gallery. Sign in and try again!" and return
    end

    params_surrogate = gallery_edit_params.dup

    existing_attachments = params_surrogate.delete(:existing_attachments)
    new_attachments = params_surrogate.delete(:attachments)

    existing_attachments.each do |att|
      attachment = Attachment.find(att[:id])
      attachment.caption = att[:caption]
      attachment.save!
    end

    if !!new_attachments
      fresh_attachments = new_attachments[:photo].map do |photo|
        Attachment.create!(photo: photo)
      end
      gallery.attachments << fresh_attachments
    end
    
    gallery.update!(params_surrogate)
    redirect_to(gallery)
  end

  def create
    attachment_params = params[:gallery].delete(:attachments)
    gallery = Gallery.create!(gallery_params)

    if attachment_params
      attachments = attachment_params[:photo].map do |photo|
        Attachment.create!(photo: photo)
      end
      gallery.attachments << attachments
      gallery.save!      
    end
    
    redirect_to(gallery)
  end

  private

  def user_owns_gallery?(gallery)
    return true if current_user == gallery.user
    return false
  end

  def gallery_params
    params.require(:gallery).permit(:user_id, :description, :title, attachments: [photo:[]])      
  end

  def gallery_edit_params
    params.require(:gallery).permit(:description, :title, existing_attachments: [:id, :caption], attachments: [photo:[]])
  end

end

app/controllers/home_controller.rb
class HomeController < InheritedResources::Base
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/attachments/_form.html.erb
<%= form_with(model: attachment) do |form| %>
  <% if attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
        <% attachment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div> 

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.caption %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@attachment.photo, width: 200) if @attachment.photo.attached? %>
<p>
  <strong>Caption:</strong>
  <%= @attachment.caption %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>

app/views/galleries/_edit_form.html.erb
<%= form_with(model: @gallery) do |form| %>
  <%= link_to 'View Gallery', @gallery %> |
  <%= link_to 'Back', galleries_path %>

  <h1>Editing Gallery</h1>

  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
        <% @gallery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>  

  <div class="field">
    <%= form.label :message %>
    <%= form.rich_text_area :description %>
  </div>

  <div class='separator'></div>

  <h4> Add Photos </h4>
  <small class='col-sm-12 row form-info'><i>You can add multiple photos at the same time by holding CTRL (or Command on Mac) and clicking on multiple files.</i></small>  
  <%= form.fields_for :attachments do |attachment| %>
    <%= attachment.file_field :photo, multiple: true %>
  <% end %>

  <div class='separator'></div>

  <h4> Edit Existing Photos </h4>
  <div class="attachment-edit-container">
    <% @gallery.attachments.each do |attachment| %>
      <div class='attachment-edit' id="attachment-<%= attachment.id %>">
        <%= image_tag(attachment.photo, class: 'attachment-edit-photo') if attachment.photo.attached? %>
        <%= form.hidden_field :attachment_ids, name: 'gallery[existing_attachments][][id]', :multiple => true, :value => attachment.id, id: "attachment-id-#{attachment.id}" %>
        <%= form.text_field :attachment_caption, class: 'attachment-edit-caption', name: 'gallery[existing_attachments][][caption]', id: "caption-#{attachment.id}", multiple: true, data: {attachment_id: attachment.id }, :value => attachment.caption, placeholder: "Enter a caption here...", id: "attachment-caption-#{attachment.id}" %>
        <a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/attachments/<%= attachment.id %>"><i class="fas fa-trash" id='delete-attachment-<%= attachment.id %>'></i></a>
        
      </div>
      
    <% end %>    
  </div>


  <div class="actions">
    <%= form.submit %>
  </div> 

  <div class='pad-after'></div>    

  <%= link_to 'View Gallery', @gallery %> |
  <%= link_to 'Back', galleries_path %>
  
<% end %>

app/views/galleries/_form.html.erb
<%= form_with(model: @gallery) do |form| %>
  <%= link_to 'Back', galleries_path %>

  <h1>New Gallery</h1>

  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
        <% @gallery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>  

  <div class="field">
    <%= form.label :message %>
    <%= form.rich_text_area :description, required: true %>
  </div>

  <div class='separator'></div>

  <h4>Add Photos</h4>
  <small class='col-sm-12 row form-info warn'><i>**You will need to create a Gallery before adding captions to photos.**</i></small>   
  <small class='col-sm-12 row form-info'><i>You can add multiple photos at the same time by holding CTRL (or Command on Mac) and clicking on multiple files in the file selection window.</i></small>
  <%= form.fields_for :attachments do |attachment| %>
    <%= attachment.file_field :photo, multiple: true %>
  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>

  <%= link_to 'Back', galleries_path %>  
<% end %>

app/views/galleries/_gallery_row.html.erb
<div class='gallery-row col-sm-12'>
  <div class='row'>

    <div class='col-sm-2 photo-container'>
      <% if gallery.has_photos? %>
        <%= image_tag gallery.first_photo, class: 'title-photo' %>
      <% else %>
        <%= image_tag "beverly-bw.png", class: 'title-photo' %>
      <% end %>    
    </div>

    <div class="col-sm-10">
      <h4 class='title'><%= gallery.title %></h4>
      <p class='contributor'>
        Contributed by: <%= gallery.user.display_name %>
        <%if gallery.user === current_user %>
          <span><%= link_to "Edit", edit_gallery_path(gallery) %></span>
        <% end %>
      </p>
      <div class='desc-wrapper'>
        <div class="desc-overlay"></div>
        <%= gallery.description %> 
       <a href="<%= gallery_path(gallery)%>" class='gallery-link'><button class='lilac-button'>See the Full Gallery</button></a> 
      </div>
    </div>  
  </div>
</div>

app/views/galleries/edit.html.erb
<%= render 'edit_form', gallery: @gallery %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<div class='gallery-container col-sm-12'>
  <h1>Galleries</h1>
  <% @galleries.each do |gallery| %>
    <%= render 'gallery_row', gallery: gallery %>
  <% end %>

  <%= link_to 'New Gallery', new_gallery_path %>  
</div>

app/views/galleries/new.html.erb
<%= render 'form', gallery: @gallery %>

app/views/galleries/show.html.erb
<div class='gallery-show'>
  <h4 class='gallery-title'><%= @gallery.title %></h4>
  <h6 class='contributor'>Contributed by: <%= @gallery.user.display_name %></h6>
  <%if @gallery.user === current_user %>
    <span><%= link_to "Edit", edit_gallery_path(@gallery) %></span>
  <% end %>
  <div class='description-container'>
    <p>
      <%= @gallery.description %>
    </p>    
  </div>


  <div class='gallery-photos-container'>
    <% @gallery.attachments.each do |attachment| %>
      <div class='polaroid'>
        <%= image_tag(attachment.photo) if attachment.photo.attached? %>
        <p><%= attachment.caption %></p>
      </div>
  
    <% end %>
  </div> 

   <%= link_to 'Back to Galleries', galleries_path %>
   
</div>

app/views/home/index.html.erb
<div class="featured-container">
  <div class='inset-container'>
    <div class='featured-photo-container'>
      <%= image_tag "beverly-bw.png" %>    
    </div>
    <div class='featured-copy-container'>
      <h3>In Loving Memory of</h3>
      <h2>Beverly Beavers</h2>
      <h6>July 14, 1928 - February 10, 2021</h6>
      <div class='action-links-container'>
        <a href="<%= new_gallery_path %>"><button class='lilac-button contribute'>Contribute a Memory</button></a></br>
        <a href="<%= galleries_path %>"><button class='lilac-button browse'>Browse Galleries</button></a>
      </div>
    </div>

  </div>
</div>

<button class='lilac-button affixed-bottom-center'>
  <p>More Below</p>
  <i class="fas fa-arrow-alt-circle-down"></i>
</button>

<div class='section-separator'>
  <h1>Slideshow</h1>
</div>

<div id="carouselControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">

    <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>    

    <% Attachment.all.each_with_index do |att, index| %>
      <div class="carousel-item <% if index == 0 %>active<% end %>">
        <%= image_tag att.photo, class: 'carousel-img-front' %>
        <div class="carousel-caption d-none d-md-block">
          <% if att.caption.present? %><p><%= att.caption %></p><% end %>
        </div>          
      </div>     
    <% end %>

  </div>

</div>

<div style="margin-bottom: 15px; box-shadow: 0px 2px 6px 2px black;" class='section-separator'>
  <h1>Galleries</h1>
</div>

<div class='gallery-container col-sm-12'>
  <% Gallery.all.each do |gallery| %>
    <%= render 'galleries/gallery_row', gallery: gallery %>
  <% end %>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beverly Beavers' Memories</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A tribute website to Beverly Beavers where her family and friends can add photos, leave memories, and view photo galleries pertaining to her life."/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">    
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karma&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>    
  <div class="navbar-main float-right col-sm-12 container">
    <div class="row">

      <div class="collapse main-nav" id="navbarToggleMobile">
        <div class="navbar-links" style='text-align: center;'>
            <% if user_signed_in? %>
              <strong>Signed In As: <%= current_user.display_name %></strong>
              <a href="<%= edit_user_registration_path %>"><button class='lilac-button'>Edit Profile</button></a>
              <a class="navbar-link" rel="nofollow" data-method="delete" href="/users/sign_out"><button class='lilac-button'>Sign Out</button></a>
            <% else %>
              <strong>Log in or Create an Account Below</strong>
              <a href="<%= new_user_registration_path %>"><button class='lilac-button'>Sign Up</button></a>
              <a href="<%= new_user_session_path %>"><button class='lilac-button'>Log In</button></a>
            <% end %>          
        </div>
            
      </div>      

      <div class='navbar-links col-lg-12 float-right align-items-center'>
        <div class='icon-wrapper'><a class="home-link" href='/'>BB</a></div>
        <div class='user-links navbar-light'>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleMobile" aria-controls="navbarToggleMobile" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>            
        </div>
    
      </div>      
    </div>


  </div>

    <%= yield %>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
 


  </body>

</html>